puppetlabs/puppetlabs-zfs_core

lib/puppet/provider/zfs/zfs.rb, lib/puppet/type/zfs.rb, spec/unit/provider/zfs/zfs_spec.rb, spec/unit/type/zfs_spec.rb
(MODULES-8823) Add `overlay` option for resource `zfs`
As described in the ticket (https://tickets.puppetlabs.com/browse/MODULES-8823) this option allows mounting over non empty directories. The current master of `zfs_core` simply doesn't implement such option on the `zfs` resource. This change allows for specification of such option in puppet modules:
```
zfs { 'my_pool/my_volume':
ensure      => present,
mountpoint  => '/mnt/non_empty_dir',
overlay     => 'on'
}
```
=> Add support for overlay option in zfs

REFERENCE.md, lib/puppet/provider/zpool/zpool.rb
This allows usage of e.g. LVs, LUKS-devices etc. with ZOL. Also currently only way (?) to use an L2ARC ("<dev> [...] cache <l2arc-dev>").
Otherwise result in errors like:
Error: zpool disk can't be changed. should be ["/dev/mapper/cryptdevice cache /dev/rootvg/l2arc"], currently is ["cryptdevice cache l2arc"]
(while the creation worked!)
Changing the devices to their short names ("cryptdevice" and "l2arc") will fix the above error, but fails to actually create the zpool (as there are no "/dev/cryptdevice" and "/dev/l2arc").
N.B.: this may actually break things on Solaris etc., if people use /dev-shortcuts there!
=> Use "zpool status -P" instead of "zpool status"

lib/puppet/provider/zfs/zfs.rb, lib/puppet/type/zfs.rb, spec/unit/provider/zfs/zfs_spec.rb, spec/unit/type/zfs_spec.rb
This reverts commit 4e1d055ece08b3fb497ea593172a38ad74d71b6f.
zfs on Solaris does not support `overlay` causing our tests to fail:
Reverting this PR.
{code}
07:03:19         puppet resource zfs tstpool/tstfs
07:03:19        Last 10 lines of output were:
07:03:19        	Error: Could not run: Execution of '/usr/sbin/zfs get -H -o value overlay tstpool/tstfs' returned 2: bad property list: invalid property 'overlay'
07:03:19        	For more info, run: zfs help get
{code}
=> Revert "(MODULES-8823) Add support for overlay option in zfs"

lib/puppet/provider/zfs/zfs.rb, lib/puppet/type/zfs.rb, spec/unit/provider/zfs/zfs_spec.rb, spec/unit/type/zfs_spec.rb
Fixed up @kali-hernandez's commit by only adding this parameter if we're running on Linux.
Adds back https://github.com/puppetlabs/puppetlabs-zfs_core/pull/20
=> (MODULES-8823) Add support for overlay option in zfs on Linux

lib/puppet/provider/zfs/zfs.rb, lib/puppet/type/zfs.rb
The zfs commands use the property value '-' to indicate that the property is not set.
We make use of this value to indicate that the `overlay` property is not set since it is not available.
The implementation added by #22 did not cover cases where the puppetserver ran on non-Linux platforms. This fixes that issue.
Passing ad-hoc: https://jenkins-master-prod-1.delivery.puppetlabs.net/view/modules/view/Core/view/zfs_core/view/adhoc/job/forge-module_puppetlabs-zfs_core_intn-sys_nightly-adhoc/6/
=> (MODULES-8823) Better handling of ZFS overlay property on Linux

spec/acceptance/tests/zpool/basic_tests_spec.rb
due to this: https://tickets.puppetlabs.com/browse/PUP-3721 the output of puppet resources has changed causing some of the tests to fail.
This PR updates the assertions.
=> (maint) fix resource assert alignment

lib/puppet/provider/zpool/zpool.rb, spec/unit/provider/zfs/zfs_spec.rb, spec/unit/provider/zpool/zpool_spec.rb
Since #14 was merged, `zpool status` output shows full paths for disks. This causes partitions to show up instead of disk devices, e.g. `/dev/sda1` for `sda`.
This would cause idempotency issues when managing zpools, due to zfs partitioning the drive:
```sh-session
> puppet resource zpool tstpool disk=/dev/sda ensure=present
Notice: /Zpool[tstpool]/ensure: created
zpool { 'tstpool':
ensure   => 'present',
disk     => ['/dev/sda1'],
provider => 'zpool',
}
> puppet resource zpool tstpool disk=/dev/sda ensure=present
Error: zpool disk can't be changed. should be ["/dev/sda"], currently is ["/dev/sda1"]
Error: /Zpool[tstpool]/disk: change from ['/dev/sda1'] to ['/dev/sda'] failed: zpool disk can't be changed. should be ["/dev/sda"], currently is ["/dev/sda1"]
> zpool status -P tstpool
pool: …
```
=> (MODULES-10592) Fix `zpool status` parsing on Linux

lib/puppet/provider/zpool/zpool.rb, lib/puppet/type/zpool.rb, spec/unit/provider/zpool/zpool_spec.rb, spec/unit/type/zpool_spec.rb
This PR adds support for setting ashift (linux only), autoexpand, and failmode on zpools, 
Both setting them individually, and also as part of creation
ashift (Only valid on linux)
autoexpand
failmode.
=> (MODULES-10726) Add support for ashift/autoexpand/failmode to the zpool provider.

lib/puppet/provider/zfs/zfs.rb
It looks like my previous PR causes a duplicate constant warning when defining both a pool and filesystem as the constant is already defined there.
I've chosen to add an unless? to the constant in zfs.rb, so that if it's already defined, it doesn't try to redefine it again.
=> (MODULES-10730) Clear duplicate constant warning when doing puppet run

lib/puppet/provider/zpool/zpool.rb
This adds a guard that prevents the `PARAMETER_UNSET_OR_NOT_AVAILABLE`
constant from being redefined in the `zpool` type.
=> (MODULES-10848) Do not redefine PARAMETER_UNSET_OR_NOT_AVAILABLE

REFERENCE.md, lib/puppet/provider/zfs/zfs.rb, lib/puppet/type/zfs.rb, spec/unit/type/zfs_spec.rb
This property controls how transactions are synchronized and it has been available since Solaris 10 8/11 release:
https://docs.oracle.com/cd/E26505_01/html/E37384/gbscy.html#gjzl
=> (MODULES-10874) Add property 'sync'

Gemfile, metadata.json
To avoid having to update this everytime we release a new agent
platform, it should be enough to specify the supported OS, without
specific versions. It is assumed that for each OS in metadata.json, the
versions supported are the same as what the agent itself supports.
Note: Puppet does not 'oficially' support ZFS on Linux (meaning we do
not test against Linux configurations and we don't commit to solve and
issues related to ZoL), so remove Linux platforms from metadata.json.
However, we happily accept community contributions that do not break any
Solaris functionality.
=> (MODULES-10953) Update metadata.json and pdk version

.devcontainer/README.md, .devcontainer/devcontainer.json, .github/workflows/auto_release.yml, .github/workflows/daily_unit_tests_with_nightly_puppet_gem.yaml, .github/workflows/release.yml, .github/workflows/static_code_analysis.yaml, .github/workflows/unit_tests_with_nightly_puppet_gem.yaml, .github/workflows/unit_tests_with_released_puppet_gem.yaml, .rubocop.yml, Gemfile, Rakefile, lib/puppet/provider/zfs/zfs.rb, lib/puppet/provider/zpool/zpool.rb, metadata.json
This commit runs `pdk update` using the most recent template at the time (2.7.1) and updates metadata.json to allow Puppet versions < 9.0.0 in preparation for the release of Puppet 8.
=> (PA-4806) Updates PDK template

.devcontainer/devcontainer.json, .github/workflows/auto_release.yml, .gitignore, .sync.yml, Gemfile, Rakefile, metadata.json, spec/spec_helper_acceptance.rb
This PR:
- Adds the voxpupuli-acceptance gem, which should re-add the Beaker rake task that was inadvertently removed in https://github.com/puppetlabs/puppetlabs-zfs_core/commit/b72a0c83b7d333426e8552b4ce472bc586d9ec53 .
- Updates the PDK template to the latest, unreleased version to pull in a new container image to fix the auto release GitHub Action.
- Pins the github_changelog_generator gem, as newer versions cause issues.
- Adds .rspec to .gitignore.
=> (maint) Follow up PDK updates

.github/workflows/auto_release.yml, .sync.yml, Gemfile
The Auto Release GitHub Action does not currently work for this repository.
This PR makes updates to the Docker image that Auto Release uses to bring in the build tools necessary to compile native extensions for gems we rely on.
It also pins the github_changelog_generator and concurrent-ruby gems.
This is based off learnings from the Support team: https://github.com/puppetlabs/puppetlabs-puppet_metrics_collector/pull/186
=> (maint) Fix auto release action

spec/acceptance/tests/zfs/basic_tests_spec.rb, spec/acceptance/tests/zfs/should_be_idempotent_spec.rb, spec/acceptance/tests/zfs/should_create_spec.rb, spec/acceptance/tests/zfs/should_query_spec.rb, spec/acceptance/tests/zfs/should_remove_spec.rb, spec/acceptance/tests/zpool/basic_tests_spec.rb, spec/acceptance/tests/zpool/should_be_idempotent_spec.rb, spec/acceptance/tests/zpool/should_create_spec.rb, spec/acceptance/tests/zpool/should_query_spec.rb, spec/acceptance/tests/zpool/should_remove_spec.rb
This PR updates several deprecated Beaker methods that were removed entirely in Beaker 5. This is in preparation for moving to Beaker 5 for tests.
=> Update deprecated Beaker methods

spec/unit/provider/zfs/zfs_spec.rb
Hi,
I noticed this typo in the code.
=> zfs_specs: fix typo in "jailed"

REFERENCE.md, lib/puppet/provider/zfs/zfs.rb, lib/puppet/type/zfs.rb
need this myself, cleaned up #76 as author was unresponsive
=> Add relatime property support to zfs

REFERENCE.md, lib/puppet/provider/zfs/zfs.rb, lib/puppet/type/zfs.rb, spec/unit/provider/zfs/zfs_spec.rb, spec/unit/type/zfs_spec.rb
May we please add the zfs attribute 'defaultuserquota' to the zfs type/provider?
=> MODULES-11423: add zfs attribute defaultuserquota

REFERENCE.md, lib/puppet/provider/zfs/zfs.rb, lib/puppet/type/zfs.rb, spec/unit/provider/zfs/zfs_spec.rb, spec/unit/type/zfs_spec.rb
This commit adds the defaultuserquota attribute. On machines with zfs filesystem version 5 and older, attempting to use this attribute causes an exception/error since defaultuserquota is not a valid attribute on older zfs filesystem versions. This commit adds logic to handle and rescue that exception.
(cherry picked from commit cb3f040d5a13eb3c0eb2e554e107a5441889dd56)
=> (PA-5790) Add zfs attribute defaultuserquota

REFERENCE.md, lib/puppet/provider/zfs/zfs.rb, lib/puppet/type/zfs.rb, spec/unit/provider/zfs/zfs_spec.rb, spec/unit/type/zfs_spec.rb
Originally commited in #79 but had caused some issues in CI. With my additional changes, this no longer causes issues.
=> Update zfs with relatime support

.sync.yml, Gemfile, spec/spec_helper_acceptance.rb
beaker-puppet_install_helper 0.9.8 cannot be used with beaker 5 hence removing the dependency.
=> (PA-6139) Drop beaker-puppet_install_helper gem in zfs-core module
